# challenge 1

Input: A single even integer 'n'.
Output: An 'n*n' NumPy array in checkerboard format.

Example:
Input 1:
2
Output 1:
[[0 1]
 [1 0]]
Input 2:
4
Output 2:
[[0 1 0 1] 
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]

In [7]:
import numpy as np
n = int(input())
print(n)

4
4


In [8]:
array_output = np.zeros( (n,n), dtype= np.int)

In [9]:
array_output[::2,1::2] = 1
array_output[1::2,::2] = 1
print(array_output)


[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]
