# challenge 1

Input: A single even integer 'n'.
Output: An 'n*n' NumPy array in checkerboard format.

Example:
Input 1:
2
Output 1:
[[0 1]
 [1 0]]
Input 2:
4
Output 2:
[[0 1 0 1] 
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]

In [10]:
#Solution
import numpy as np
n = int(input())
array_output = np.zeros( (n,n), dtype= np.int)
array_output[::2,1::2] = 1
array_output[1::2,::2] = 1
print(array_output)


4
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


# challenge 2
Description
Extract all the border rows and columns from a 2-D array.



Format:

Input: A 2-D Python list

Output: Four NumPy arrays - print first column of the input array, first row of the input array, last column of the input array, last row of the input array respectively.



Example:

Input 1:

[[11 12 13 14]

 [21 22 23 24]

 [31 32 33 34]]

Output 1:

[11 21 31]

[11 12 13 14]

[14 24 34]

[31 32 33 34]

In [14]:
#Solution

input_list = [[11 ,12, 13, 14],[21, 22 ,23 ,24],[31 ,32 ,33 ,34]]

import numpy as np

# Convert the input list to a NumPy array
array_2d =np.array(input_list)

# Extract the first column, first row, last column and last row respectively using
# appropriate indexing
col_first = array_2d[:,0]
row_first = array_2d[0,:]
col_last = array_2d[:,-1]
row_last = array_2d[-1,:]

print(col_first)
print(row_first)
print(col_last)
print(row_last)



[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]
